name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests
      run: npm test
      
    - name: Build plugin
      run: npm run build
      
    - name: Create release assets
      run: |
        mkdir release
        cp main.js manifest.json styles.css release/
        cd release && zip -r ../obsidian-journal-plugin-${{ github.ref_name }}.zip .
        
    - name: Create release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release create ${{ github.ref_name }} \
          --title "Release ${{ github.ref_name }}" \
          --notes "## Changes

        See [CHANGELOG.md](CHANGELOG.md) for details.

        ## Installation

        ### Manual Installation
        1. Download \`main.js\`, \`manifest.json\`, and \`styles.css\` from the assets below
        2. Create a folder \`obsidian-journal-plugin\` in your vault's \`.obsidian/plugins/\` directory
        3. Copy the downloaded files into the folder
        4. Reload Obsidian and enable the plugin in Community Plugins settings

        ### From Release
        1. Download the \`obsidian-journal-plugin-${{ github.ref_name }}.zip\` file below
        2. Extract it to your vault's \`.obsidian/plugins/\` directory
        3. Reload Obsidian and enable the plugin" \
          main.js \
          manifest.json \
          styles.css \
          obsidian-journal-plugin-${{ github.ref_name }}.zip